# -*- coding: utf-8 -*-
"""tugas.2.1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PjQ5pWzEl3NhXeH-1uTiRbzVEJUidtaa
"""

artikel = 'Banyak mahasiswa sekarang belajar programming menggunakan \
bahasa seperti Python, JavaScript, Java, dan C++ untuk membangun aplikasi.'

print('Python' in artikel)
print('PHP' in artikel)

nama = 'Digital Marketing'

print(nama[2])
print(nama[8])
print(nama[-1])
print(nama[-4])

print(len('Surabaya'))
print(len('Jakarta'))

email_1 = 'admin@gmail.com'
email_2 = 'user@yahoo.com'
email_3 = 'contact@gmail.com'

domain = 'admin'

print(email_1.startswith(domain))
print(email_2.startswith(domain))
print(email_3.startswith(domain))

file_1 = 'laporan.pdf'
file_2 = 'gambar.png'

print(file_1.endswith('.pdf'))
print(file_2.endswith('.pdf'))