# -*- coding: utf-8 -*-
"""UTS .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12n3xMAQiF4Ht7cP8-F2vg2dh0KjLrnJd
"""

# =========================================
# LAPORAN HARIAN KEDAI SOU SPACE
# (Versi sederhana - gaya mahasiswa)
# =========================================

# Data dari soal (WAJIB SAMA)
raw_log = "ID:001#NAMA:kopi susu gula\naren#QTY:3#PRICE:18000;ID:002#NAMA:COFFEE LATTE#QTY:1#PRICE:25000"

# =========================================
# 1. SPLIT DATA
# =========================================

# Pisahkan jadi 2 transaksi pakai ;
data = raw_log.split(";")

# Ambil masing-masing transaksi
trx1 = data[0]
trx2 = data[1]

# Pecah lagi pakai #
t1 = trx1.split("#")
t2 = trx2.split("#")

# =========================================
# 2. CLEANING DATA
# =========================================

# Transaksi 1
id1 = t1[0].replace("ID:", "").strip()
nama1 = t1[1].replace("NAMA:", "").replace("\n", " ").strip()
qty1 = t1[2].replace("QTY:", "").strip()
harga1 = t1[3].replace("PRICE:", "").strip()

# Transaksi 2
id2 = t2[0].replace("ID:", "").strip()
nama2 = t2[1].replace("NAMA:", "").strip()
qty2 = t2[2].replace("QTY:", "").strip()
harga2 = t2[3].replace("PRICE:", "").strip()

# =========================================
# 3. TRANSFORMASI
# =========================================

# Biar rapi → huruf awal besar
nama1 = nama1.title()
nama2 = nama2.title()

# Ubah ke angka
qty1 = int(qty1)
harga1 = int(harga1)

qty2 = int(qty2)
harga2 = int(harga2)

# =========================================
# 4. HITUNG TOTAL
# =========================================

subtotal1 = qty1 * harga1
subtotal2 = qty2 * harga2

total = subtotal1 + subtotal2

# =========================================
# 5. OUTPUT (dibuat sederhana & rapi)
# =========================================

print("="*55)
print("        LAPORAN HARIAN KEDAI SOU SPACE")
print("="*55)

print("MENU                     QTY     HARGA     SUBTOTAL")
print("-"*55)

print(f"{nama1:<25}{qty1:<8}{harga1:<10}{subtotal1}")
print(f"{nama2:<25}{qty2:<8}{harga2:<10}{subtotal2}")

print("-"*55)
print(f"TOTAL PENDAPATAN HARI INI:     Rp {total}")
print("="*55)

# =========================================
# LAPORAN HARIAN KEDAI SOU SPACE
# =========================================

# data dari soal (copy aja)
raw_log = "ID:001#NAMA:kopi susu gula\naren#QTY:3#PRICE:18000;ID:002#NAMA:COFFEE LATTE#QTY:1#PRICE:25000"

# =========================
# pisahin dulu jadi 2 transaksi
# =========================
data = raw_log.split(";")

trx1 = data[0]
trx2 = data[1]

# pecah lagi pake #
t1 = trx1.split("#")
t2 = trx2.split("#")

# =========================
# ambil datanya (clean dikit)
# =========================

# transaksi 1
id1 = t1[0].replace("ID:", "").strip()
nama1 = t1[1].replace("NAMA:", "").replace("\n", " ").strip()
qty1 = t1[2].replace("QTY:", "").strip()
harga1 = t1[3].replace("PRICE:", "").strip()

# transaksi 2
id2 = t2[0].replace("ID:", "").strip()
nama2 = t2[1].replace("NAMA:", "").strip()
qty2 = t2[2].replace("QTY:", "").strip()
harga2 = t2[3].replace("PRICE:", "").strip()

# =========================
# rapihin dikit
# =========================

nama1 = nama1.title()
nama2 = nama2.title()

qty1 = int(qty1)
harga1 = int(harga1)

qty2 = int(qty2)
harga2 = int(harga2)

# =========================
# hitung total
# =========================

sub1 = qty1 * harga1
sub2 = qty2 * harga2

total = sub1 + sub2

# =========================
# print hasilnya
# =========================

print("="*55)
print("            LAPORAN HARIAN KEDAI SOU SPACE")

print("="*55)
print("MENU                       QTY     HARGA     SUBTOTAL")
print("-"*55)

print(f"{nama1:<25}{qty1:>5}{harga1:>10}{sub1:>12}")
print(f"{nama2:<25}{qty2:>5}{harga2:>10}{sub2:>12}")

print("-"*55)
print("TOTAL PENDAPATAN HARI INI:     Rp",                    total)
print("="*55)